[project]
name = "supplemental-tax-rolls-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "josephadogeriopao", email = "joseph.adogeri@orleansassessors.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
supplemental-tax-rolls-generator = "supplemental_tax_rolls_generator:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
